name: "3/4 Bar Play Watchlist"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
      - name: Install Dependencies (Driver and Headless) # Using shell script to install Google Chrome
        run: |
          make fetch-dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t lib
          export PYTHONPATH=lib
          export PATH=bin
      - name: Execute main script # run main.py to get the latest data
        run: python main.py